# Simple workflow for deploying static content to GitHub Pages
name: Build Development Version

on:
  # Runs on pushes targeting the default branch
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        requied: true
        type: string
      version:
        description: 'Version (v0.0.0)'
        requied: true
        type: string
      mode:
        description: 'Mode'
        type: choice
        options:
          - dev
          - prod

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  NODE_VERSION: 20

jobs:
  # Single deploy job since we're just deploying
  build:
    name: Build Game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Build Project
        run: pnpm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  pages:
    name: Publish Site
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  dev-release:
    name: Release Dev Build
    if: inputs.mode == 'dev'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Create Zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r game.zip dist

       
      #- uses: "marvinpinto/action-automatic-releases@latest"
      - uses: "mathieucarbou/marvinpinto-action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev-${{ inputs.version }}"
          prerelease: true
          title: "Development Build (${{ inputs.version}})"
          files: |
            game.zip
  prod-release:
    name: Release Production Build
    if: inputs.mode == 'prod'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Create Zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r game.zip dist

       
      #- uses: "marvinpinto/action-automatic-releases@latest"
      - uses: "mathieucarbou/marvinpinto-action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev-${{ inputs.version }}"
          prerelease: true
          title: "${{ inputs.name }} (${{ inputs.version}})"
          files: |
            game.zip