# Simple workflow for deploying static content to GitHub Pages
name: Build Development Version

on:
  # Runs on pushes targeting the default branch
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        requied: false
        default: ''
        type: string
      bump:
         description: 'Version Bump'
         type: choice
         options:
            - patch
            - minor
            - major

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  NODE_VERSION: 20

jobs:
  # Single deploy job since we're just deploying
  build:
    name: Build Game

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Build Project
        run: pnpm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  pages:
    name: Publish Site
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  dev-release:
    name: Release Dev Build
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Create Zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r game.zip dist

      - name: Get previous tag
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        with:
          fallback: 'v0.0.0'
          prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: 'Publish Patch Release'
        if: inputs.bump == 'patch'
        run: "gh release create ${{ steps.semvers.outputs.v_patch }} --generate-notes -t 'Patch: ${{ inputs.name }} ${{ steps.semvers.outputs.v_patch }}' -p ./game.zip"
        env:
          GH_TOKEN: ${{ github.token }}
      
      - name: 'Publish Minor Release'
        run: "gh release create ${{ steps.semvers.outputs.v_minor }} --generate-notes -t 'Minor: ${{ inputs.name }} ${{ steps.semvers.outputs.v_minor }}' -p ./game.zip"
        if: inputs.bump == 'minor'
        env:
          GH_TOKEN: ${{ github.token }}
      - name: 'Publish Major Release'
        if: inputs.bump == 'major'
        run: "gh release create ${{ steps.semvers.outputs.v_major }} --generate-notes -t 'Major: ${{ inputs.name }} ${{ steps.semvers.outputs.v_major }}' -p ./game.zip"
        env:
          GH_TOKEN: ${{ github.token }}
      #- uses: "marvinpinto/action-automatic-releases@latest" 